In [1]:
import pandas as pd

In [7]:
DFFort =pd.read_csv('fortune1000.csv', index_col='Rank')
DFFort.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [8]:
DFFort.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 1 to 1000
Data columns (total 7 columns):
Company      1000 non-null object
Sector       1000 non-null object
Industry     1000 non-null object
Location     1000 non-null object
Revenue      1000 non-null int64
Profits      1000 non-null int64
Employees    1000 non-null int64
dtypes: int64(3), object(4)
memory usage: 62.5+ KB

In [14]:
s = DFFort.groupby(by='Sector')

In [20]:
len(s)

21

In [21]:
len(DFFort)

1000

In [45]:
s.groups

{'Aerospace & Defense': Int64Index([ 24,  45,  60,  88, 118, 120, 209, 245, 282, 378, 389, 490, 560,
             605, 785, 788, 836, 903, 958, 987],
            dtype='int64', name='Rank'),
 'Apparel': Int64Index([91, 231, 340, 354, 448, 547, 575, 597, 683, 695, 726, 794, 877,
             882, 917],
            dtype='int64', name='Rank'),
 'Business Services': Int64Index([144, 186, 199, 204, 221, 248, 249, 294, 307, 312, 355, 392, 404,
             440, 467, 468, 481, 485, 492, 503, 545, 626, 635, 652, 677, 694,
             714, 729, 734, 735, 737, 744, 767, 776, 777, 783, 791, 792, 796,
             801, 803, 816, 819, 820, 869, 870, 886, 939, 951, 952, 993],
            dtype='int64', name='Rank'),
 'Chemicals': Int64Index([ 56, 101, 182, 189, 206, 253, 262, 277, 288, 296, 316, 538, 549,
             555, 566, 580, 613, 624, 654, 668, 717, 720, 724, 758, 761, 829,
             865, 898, 934, 949],
            dtype='int64', name='Rank'),
 'Energy': Int64Index([  2,  14,  30,  32,  42,  65,  90,  95,  98, 104,
             ...
             953, 955, 962, 966, 980, 981, 983, 995, 997, 997],
            dtype='int64', name='Rank', length=122),
 'Engineering & Construction': Int64Index([155, 156, 235, 260, 301, 314, 352, 381, 433, 478, 498, 501, 516,
             572, 576, 640, 719, 738, 822, 863, 874, 892, 929, 963, 985, 994],
            dtype='int64', name='Rank'),
 'Financials': Int64Index([  4,  16,  23,  26,  27,  29,  35,  40,  43,  49,
             ...
             920, 923, 925, 926, 936, 938, 959, 976, 988, 996],
            dtype='int64', name='Rank', length=139),
 'Food and Drug Stores': Int64Index([7, 17, 19, 87, 107, 160, 181, 595, 614, 631, 669, 756, 809, 849,
             928],
            dtype='int64', name='Rank'),
 'Food, Beverages & Tobacco': Int64Index([ 41,  44,  62,  66,  84,  94, 106, 149, 153, 161, 176, 207, 215,
             242, 266, 304, 336, 337, 362, 397, 413, 429, 452, 456, 460, 535,
             542, 567, 574, 587, 608, 615, 636, 664, 686, 702, 770, 787, 795,
             804, 889, 902, 954],
            dtype='int64', name='Rank'),
 'Health Care': Int64Index([  5,   6,  12,  21,  22,  33,  39,  46,  52,  55,  63,  72,  79,
              86, 123, 124, 125, 130, 138, 140, 141, 168, 172, 200, 201, 202,
             263, 268, 278, 286, 287, 290, 291, 305, 325, 358, 359, 372, 420,
             430, 431, 447, 457, 465, 469, 515, 527, 537, 553, 559, 583, 618,
             629, 661, 684, 693, 697, 708, 746, 749, 766, 775, 790, 799, 815,
             818, 845, 868, 881, 883, 935, 960, 965, 977, 978],
            dtype='int64', name='Rank'),
 'Hotels, Resturants & Leisure': Int64Index([109, 146, 195, 218, 241, 254, 309, 371, 444, 466, 534, 546, 557,
             562, 585, 731, 763, 764, 779, 797, 895, 915, 918, 941, 999],
            dtype='int64', name='Rank'),
 'Household Products': Int64Index([ 34, 151, 174, 256, 261, 328, 338, 345, 370, 434, 441, 450, 455,
             533, 550, 554, 601, 665, 699, 716, 856, 890, 900, 907, 932, 950,
             967, 992],
            dtype='int64', name='Rank'),
 'Industrials': Int64Index([  11,   59,   75,   93,   97,  128,  134,  148,  211,  224,  360,
              377,  396,  412,  419,  539,  544,  596,  622,  623,  630,  645,
              655,  658,  666,  674,  690,  757,  782,  789,  806,  813,  823,
              831,  832,  835,  841,  847,  866,  867,  873,  887,  942,  947,
              964, 1000],
            dtype='int64', name='Rank'),
 'Materials': Int64Index([126, 127, 170, 244, 251, 303, 321, 341, 356, 373, 375, 383, 417,
             418, 426, 435, 446, 480, 489, 514, 518, 577, 586, 616, 617, 620,
             625, 628, 637, 639, 641, 660, 667, 687, 691, 751, 774, 793, 857,
             885, 911, 982, 986],
            dtype='int64', name='Rank'),
 'Media': Int64Index([ 53,  96,  99, 203, 213, 255, 327, 366, 406, 414, 525, 530, 681,
             705, 707, 722, 741, 752, 759, 762, 821, 913, 968, 969, 989],
            dtype='int64', name='Rank'),
 'Motor Vehicles & Parts': Int64Index([  8,   9,  70, 147, 154, 169, 281, 310, 334, 339, 424, 428, 470,
             588, 591, 604, 647, 670, 718, 739, 811, 957, 961, 979],
            dtype='int64', name='Rank'),
 'Retailing': Int64Index([  1,  15,  28,  38,  47,  71,  89, 103, 111, 132, 136, 139, 143,
             145, 177, 180, 191, 196, 197, 228, 234, 237, 238, 240, 258, 267,
             269, 280, 293, 297, 299, 302, 330, 342, 346, 361, 365, 374, 379,
             380, 393, 415, 427, 439, 495, 500, 502, 511, 512, 517, 523, 582,
             592, 602, 607, 610, 621, 643, 644, 648, 657, 675, 689, 721, 748,
             771, 773, 807, 812, 824, 825, 827, 840, 876, 894, 899, 922, 937,
             940, 973],
            dtype='int64', name='Rank'),
 'Technology': Int64Index([  3,  18,  20,  25,  31,  36,  51,  54,  77, 110,
             ...
             931, 943, 944, 946, 956, 970, 971, 975, 984, 990],
            dtype='int64', name='Rank', length=102),
 'Telecommunications': Int64Index([10, 13, 37, 116, 159, 187, 292, 333, 399, 443, 461, 496, 526, 619,
             786],
            dtype='int64', name='Rank'),
 'Transportation': Int64Index([ 48,  58,  67,  68,  80, 129, 142, 208, 239, 270, 353, 390, 395,
             405, 407, 416, 432, 459, 521, 528, 570, 578, 642, 672, 709, 713,
             740, 800, 814, 858, 884, 930, 933, 945, 972, 974],
            dtype='int64', name='Rank'),
 'Wholesalers': Int64Index([ 57,  64,  92, 102, 108, 119, 122, 167, 183, 185, 212, 276, 285,
             315, 317, 320, 323, 335, 351, 357, 369, 391, 423, 463, 474, 477,
             484, 564, 581, 599, 627, 653, 685, 727, 747, 780, 808, 837, 875,
             991],
            dtype='int64', name='Rank')}

In [70]:
DFFort.head(2)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600

In [49]:
s.get_group(name='Energy')
s.get_group(name='Retailing')

,Company,Employees,Industry,Location,Profits,Revenue
Rank,,,,,,
1,Walmart,2300000,General Merchandisers,"Bentonville, AR",14694,482130
15,Costco,161000,Specialty Retailers: Other,"Issaquah, WA",2377,116199
28,Home Depot,385000,Specialty Retailers: Other,"Atlanta, GA",7009,88519
38,Target,341000,General Merchandisers,"Minneapolis, MN",3363,73785
47,Lowe’s,225000,Specialty Retailers: Other,"Mooresville, NC",2546,59074
71,Best Buy,125000,Specialty Retailers: Other,"Richfield, MN",897,39745
89,TJX,216000,Specialty Retailers: Apparel,"Framingham, MA",2278,30945
103,Macy’s,157500,General Merchandisers,"Cincinnati, OH",1072,27079
111,Sears Holdings,178000,General Merchandisers,"Hoffman Estates, IL",-1129,25146
132,Staples,58963,Specialty Retailers: Other,"Framingham, MA",379,21059
136,AutoNation,26000,"Automotive Retailing, Services","Fort Lauderdale, FL",443,20862
139,Dollar General,113400,General Merchandisers,"Goodlettsville, TN",1165,20369
143,Penske Automotive Group,23000,"Automotive Retailing, Services","Bloomfield Hills, MI",326,19361
145,Kohl’s,86000,General Merchandisers,"Menomonee Falls, WI",673,19204
177,Gap,141000,Specialty Retailers: Apparel,"San Francisco, CA",920,15797
180,Dollar Tree,111550,Specialty Retailers: Other,"Chesapeake, VA",282,15498
191,CarMax,22064,"Automotive Retailing, Services","Richmond, VA",597,14874
196,Office Depot,49000,Specialty Retailers: Other,"Boca Raton, FL",8,14485
197,Nordstrom,72500,General Merchandisers,"Seattle, WA",600,14437
228,J.C. Penney,105000,General Merchandisers,"Plano, TX",-513,12625
234,L Brands,55400,Specialty Retailers: Apparel,"Columbus, OH",1253,12154
237,Ross Stores,77800,Specialty Retailers: Apparel,"Dublin, CA",1021,11940
238,Bed Bath & Beyond,60000,Specialty Retailers: Other,"Union, NJ",958,11881
240,Toys “R” Us,62000,Specialty Retailers: Other,"Wayne, NJ",-130,11802
258,Murphy USA,7100,Specialty Retailers: Other,"El Dorado, AR",176,10885
267,Group 1 Automotive,12886,"Automotive Retailing, Services","Houston, TX",94,10633
269,Hertz Global Holdings,30000,"Automotive Retailing, Services","Estero, FL",273,10535
280,AutoZone,63990,Specialty Retailers: Other,"Memphis, TN",1160,10187
293,Advance Auto Parts,56500,Specialty Retailers: Other,"Roanoke, VA",473,9737
297,Sonic Automotive,9800,"Automotive Retailing, Services","Charlotte, NC",86,9624
...,...,...,...,...,...,...
523,Ascena Retail Group,31000,Specialty Retailers: Apparel,"Mahwah, NJ",-237,4803
582,Tiffany,12200,Specialty Retailers: Other,"New York, NY",464,4105
592,Cabela’s,19700,Specialty Retailers: Other,"Sidney, NE",189,3998
602,Ulta Salon Cosmetics & Fragrance,18100,Specialty Retailers: Other,"Bolingbrook, IL",320,3924
607,Fastenal,20746,Specialty Retailers: Other,"Winona, MN",516,3869
610,Sally Beauty Holdings,21033,Specialty Retailers: Other,"Denton, TX",235,3834
621,HSN,6600,Specialty Retailers: Other,"St. Petersburg, FL",169,3691
643,American Eagle Outfitters,22150,Specialty Retailers: Apparel,"Pittsburgh, PA",218,3522
644,Abercrombie & Fitch,28500,Specialty Retailers: Apparel,"New Albany, OH",36,3519
648,Tailored Brands,21250,Specialty Retailers: Apparel,"Houston, TX",-1027,3496
657,Urban Outfitters,16680,Specialty Retailers: Apparel,"Philadelphia, PA",225,3445
675,Rent-A-Center,24300,Specialty Retailers: Other,"Plano, TX",-867,3278
689,Aaron’s,12700,Specialty Retailers: Other,"Atlanta, GA",136,3180
721,Genesco,18363,Specialty Retailers: Apparel,"Nashville, TN",95,3022
748,Systemax,3300,Specialty Retailers: Other,"Port Washington, NY",-100,2908
771,PriceSmart,7592,Specialty Retailers: Other,"San Diego, CA",89,2803
773,Bon-Ton Stores,24100,General Merchandisers,"York, PA",-57,2790
807,Chico’s FAS,14755,Specialty Retailers: Apparel,"Fort Myers, FL",2,2642
812,DSW,11900,Specialty Retailers: Apparel,"Columbus, OH",136,2620
824,Caleres,11000,Specialty Retailers: Apparel,"St. Louis, MO",82,2577
825,PC Connection,2155,Specialty Retailers: Other,"Merrimack, NH",47,2574
827,Mattress Firm Holding,7186,Specialty Retailers: Other,"Houston, TX",65,2547
840,J.Crew Group,10450,Specialty Retailers: Apparel,"New York, NY",-1243,2506
876,Express,10710,Specialty Retailers: Apparel,"Columbus, OH",117,2350
894,Party City Holdco,12888,Specialty Retailers: Other,"Elmsford, NY",11,2295
899,Sears Hometown & Outlet Stores,2918,Specialty Retailers: Other,"Hoffman Estates, IL",-27,2288
922,Outerwall,2670,Specialty Retailers: Other,"Bellevue, WA",44,2195
937,hhgregg,4941,Specialty Retailers: Other,"Indianapolis, IN",-133,2129
940,Restoration Hardware,4200,Specialty Retailers: Other,"Corte Madera, CA",91,2109
973,99 Cents Only Stores,18200,Specialty Retailers: Other,"Commerce, CA",-232,1999

In [75]:
s.first()
s.sum()
s.get_group('Retailing')['Employees'].sum()
s["Profits"].max()
s.get_group('Retailing')['Employees'].max
s['Location','Employees','Profits'].min()

                                            Location  Employees  Profits
Sector
Aerospace & Defense                       Berwyn, PA       6955     -240
Apparel                                  Atlanta, GA       5978       82
Business Services                      Arlington, VA       2400    -1481
Chemicals                              Allentown, PA       1979     -816
Energy                                     Akron, OH        480   -23119
Engineering & Construction               Atlanta, GA       1036     -155
Financials                               Atlanta, GA        187    -1194
Food and Drug Stores                      Austin, TX       1616      -62
Food, Beverages & Tobacco            Arden Hills, MN       1857     -253
Health Care                          Abbott Park, IL       2924     -458
Hotels, Resturants & Leisure           Ann Arbor, MI       8500    -1394
Household Products                       Atlanta, GA       4406    -1149
Industrials                   Annapolis Junction, MD       4104    -6126
Materials                                Atlanta, GA         52    -1642
Media                              Beverly Hills, CA       2341     -881
Motor Vehicles & Parts                     Akron, OH       2700     -889
Retailing                                 Ankeny, IA       2155    -1243
Technology                              Angleton, TX       2285    -4359
Telecommunications                      Bethpage, NY       2700     -271
Transportation                           Atlanta, GA       1223     -191
Wholesalers                              Atlanta, GA        500     -502

Grouping by Multiple Columns

In [97]:
g = DFFort.groupby(['Sector','Industry'])

In [100]:
g['Profits','Employees'].mean()

                                                                               Profits  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                           1437.100000
Apparel                    Apparel                                          549.066667
Business Services          Advertising, marketing                           774.500000
                           Diversified Outsourcing Services                 307.500000
                           Education                                         23.000000
                           Financial Data Services                          918.736842
                           Miscellaneous                                    710.000000
                           Temporary Help                                   200.000000
                           Waste Management                                 343.600000
Chemicals                  Chemicals                                        754.266667
Energy                     Energy                                          -931.285714
                           Mining, Crude-Oil Production                   -4448.392857
                           Miscellaneous                                    476.000000
                           Oil and Gas Equipment, Services                 -449.666667
                           Petroleum Refining                              1875.764706
                           Pipelines                                        484.500000
                           Utilities: Gas and Electric                      732.073171
Engineering & Construction Engineering, Construction                        126.071429
                           Homebuilders                                     294.916667
Financials                 Commercial Banks                                4634.285714
                           Diversified Financials                          1903.200000
                           Insurance: Life, Health (Mutual)                 560.100000
                           Insurance: Life, Health (stock)                 1096.166667
                           Insurance: Property and Casualty (Mutual)       1147.285714
                           Insurance: Property and Casualty (Stock)        1600.107143
                           Real estate                                      632.000000
                           Securities                                       791.944444
Food and Drug Stores       Food and Drug Stores                            1117.266667
Food, Beverages & Tobacco  Beverages                                       1299.777778
                           Food Consumer Products                           963.150000
...                                                                                ...
Materials                  Metals                                          -160.071429
                           Miscellaneous                                      7.000000
                           Packaging, Containers                            277.812500
Media                      Entertainment                                   1427.000000
                           Publishing, Printing                            -191.285714
Motor Vehicles & Parts     Motor Vehicles and Parts                        1079.083333
Retailing                  Automotive Retailing, Services                   255.000000
                           General Merchandisers                           2013.700000
                           Specialty Retailers: Apparel                     254.611111
                           Specialty Retailers: Other                       489.523810
Technology                 Computer Peripherals                             993.750000
                           Computer Software                               1889.785714
                           Computers, Office Equipment                     8347.571429
                           Information Technology Services                 1261.692308
                           Internet Services and Retailing                 1482.133333
                           Network and Other Communications Equipment      1350.500000
                           Scientific,Photographic and Control Equipment    778.833333
                           Semiconductors and Other Electronic Components  1074.826087
Telecommunications         Telecommunications                              3242.466667
Transportation             Airlines                                        2644.444444
                           Mail, Package, and Freight Delivery             2947.000000
                           Miscellaneous                                    227.000000
                           Railroads                                       1801.000000
                           Transportation Equipment                         487.600000
                           Transportation and Logistics                     179.000000
                           Trucking, Truck Leasing                          212.222222
Wholesalers                Miscellaneous                                     17.000000
                           Wholesalers: Diversified                         207.720000
                           Wholesalers: Electronics and Office Equipment    232.125000
                           Wholesalers: Food and Grocery                    194.333333

                                                                               Employees
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                            48402.850000
Apparel                    Apparel                                          23093.133333
Business Services          Advertising, marketing                           62050.000000
                           Diversified Outsourcing Services                 50595.000000
                           Education                                        15585.000000
                           Financial Data Services                          13943.473684
                           Miscellaneous                                    12573.333333
                           Temporary Help                                   12004.000000
                           Waste Management                                 23839.800000
Chemicals                  Chemicals                                        15455.033333
Energy                     Energy                                            5005.142857
                           Mining, Crude-Oil Production                      5325.357143
                           Miscellaneous                                     6700.000000
                           Oil and Gas Equipment, Services                  25088.333333
                           Petroleum Refining                               14404.705882
                           Pipelines                                         6011.750000
                           Utilities: Gas and Electric                      10249.487805
Engineering & Construction Engineering, Construction                        26293.142857
                           Homebuilders                                      3217.000000
Financials                 Commercial Banks                                 54965.142857
                           Diversified Financials                           21940.933333
                           Insurance: Life, Health (Mutual)                  5880.100000
                           Insurance: Life, Health (stock)                  11235.166667
                           Insurance: Property and Casualty (Mutual)        19021.142857
                           Insurance: Property and Casualty (Stock)         28361.535714
                           Real estate                                      10705.266667
                           Securities                                        7940.333333
Food and Drug Stores       Food and Drug Stores                             93026.533333
Food, Beverages & Tobacco  Beverages                                        22123.000000
                           Food Consumer Products                           33271.950000
...                                                                                  ...
Materials                  Metals                                           13825.642857
                           Miscellaneous                                       52.000000
                           Packaging, Containers                            20840.375000
Media                      Entertainment                                    21309.111111
                           Publishing, Printing                             23821.428571
Motor Vehicles & Parts     Motor Vehicles and Parts                         45106.666667
Retailing                  Automotive Retailing, Services                   17497.400000
                           General Merchandisers                           340810.000000
                           Specialty Retailers: Apparel                     42807.944444
                           Specialty Retailers: Other                       44619.333333
Technology                 Computer Peripherals                             43814.750000
                           Computer Software                                27771.142857
                           Computers, Office Equipment                      66869.285714
                           Information Technology Services                  75818.384615
                           Internet Services and Retailing                  28723.666667
                           Network and Other Communications Equipment       21379.285714
                           Scientific,Photographic and Control Equipment    19291.750000
                           Semiconductors and Other Electronic Components   26065.391304
Telecommunications         Telecommunications                               55497.866667
Transportation             Airlines                                         43511.222222
                           Mail, Package, and Freight Delivery             332137.500000
                           Miscellaneous                                     4200.000000
                           Railroads                                        24368.800000
                           Transportation Equipment                         11945.200000
                           Transportation and Logistics                     24938.200000
                           Trucking, Truck Leasing                          18939.555556
Wholesalers                Miscellaneous                                     9200.000000
                           Wholesalers: Diversified                          9353.240000
                           Wholesalers: Electronics and Office Equipment    20832.625000
                           Wholesalers: Food and Grocery                    19317.500000

[79 rows x 2 columns]

.agg() Method #can be called on a groupby() variable

In [113]:
g.agg(('sum','mean'))
g.agg({'Revenue':'sum',
        'Profits':'mean'})

                                                                           Revenue  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                            357940
Apparel                    Apparel                                           95968
Business Services          Advertising, marketing                            22748
                           Diversified Outsourcing Services                  64829
                           Education                                          7485
                           Financial Data Services                          100778
                           Miscellaneous                                     11185
                           Temporary Help                                    34716
                           Waste Management                                  30454
Chemicals                  Chemicals                                        243897
Energy                     Energy                                            67749
                           Mining, Crude-Oil Production                     176435
                           Miscellaneous                                      3159
                           Oil and Gas Equipment, Services                   82827
                           Petroleum Refining                               705472
                           Pipelines                                        138756
                           Utilities: Gas and Electric                      343411
Engineering & Construction Engineering, Construction                         99774
                           Homebuilders                                      54209
Financials                 Commercial Banks                                 623669
                           Diversified Financials                           327075
                           Insurance: Life, Health (Mutual)                 181336
                           Insurance: Life, Health (stock)                  245551
                           Insurance: Property and Casualty (Mutual)        143682
                           Insurance: Property and Casualty (Stock)         548027
                           Real estate                                       62748
                           Securities                                        85071
Food and Drug Stores       Food and Drug Stores                             483769
Food, Beverages & Tobacco  Beverages                                         79396
                           Food Consumer Products                           238954
...                                                                            ...
Materials                  Metals                                            99925
                           Miscellaneous                                      6070
                           Packaging, Containers                            105965
Media                      Entertainment                                    186276
                           Publishing, Printing                              34488
Motor Vehicles & Parts     Motor Vehicles and Parts                         482540
Retailing                  Automotive Retailing, Services                   113823
                           General Merchandisers                            684320
                           Specialty Retailers: Apparel                     122975
                           Specialty Retailers: Other                       543958
Technology                 Computer Peripherals                              48950
                           Computer Software                                179112
                           Computers, Office Equipment                      353781
                           Information Technology Services                  166067
                           Internet Services and Retailing                  259136
                           Network and Other Communications Equipment       125697
                           Scientific,Photographic and Control Equipment     65832
                           Semiconductors and Other Electronic Components   179025
Telecommunications         Telecommunications                               461834
Transportation             Airlines                                         158948
                           Mail, Package, and Freight Delivery              105816
                           Miscellaneous                                      2148
                           Railroads                                         48554
                           Transportation Equipment                          23855
                           Transportation and Logistics                      33237
                           Trucking, Truck Leasing                           35950
Wholesalers                Miscellaneous                                      8982
                           Wholesalers: Diversified                         176138
                           Wholesalers: Electronics and Office Equipment    147906
                           Wholesalers: Food and Grocery                    111774

                                                                               Profits
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                           1437.100000
Apparel                    Apparel                                          549.066667
Business Services          Advertising, marketing                           774.500000
                           Diversified Outsourcing Services                 307.500000
                           Education                                         23.000000
                           Financial Data Services                          918.736842
                           Miscellaneous                                    710.000000
                           Temporary Help                                   200.000000
                           Waste Management                                 343.600000
Chemicals                  Chemicals                                        754.266667
Energy                     Energy                                          -931.285714
                           Mining, Crude-Oil Production                   -4448.392857
                           Miscellaneous                                    476.000000
                           Oil and Gas Equipment, Services                 -449.666667
                           Petroleum Refining                              1875.764706
                           Pipelines                                        484.500000
                           Utilities: Gas and Electric                      732.073171
Engineering & Construction Engineering, Construction                        126.071429
                           Homebuilders                                     294.916667
Financials                 Commercial Banks                                4634.285714
                           Diversified Financials                          1903.200000
                           Insurance: Life, Health (Mutual)                 560.100000
                           Insurance: Life, Health (stock)                 1096.166667
                           Insurance: Property and Casualty (Mutual)       1147.285714
                           Insurance: Property and Casualty (Stock)        1600.107143
                           Real estate                                      632.000000
                           Securities                                       791.944444
Food and Drug Stores       Food and Drug Stores                            1117.266667
Food, Beverages & Tobacco  Beverages                                       1299.777778
                           Food Consumer Products                           963.150000
...                                                                                ...
Materials                  Metals                                          -160.071429
                           Miscellaneous                                      7.000000
                           Packaging, Containers                            277.812500
Media                      Entertainment                                   1427.000000
                           Publishing, Printing                            -191.285714
Motor Vehicles & Parts     Motor Vehicles and Parts                        1079.083333
Retailing                  Automotive Retailing, Services                   255.000000
                           General Merchandisers                           2013.700000
                           Specialty Retailers: Apparel                     254.611111
                           Specialty Retailers: Other                       489.523810
Technology                 Computer Peripherals                             993.750000
                           Computer Software                               1889.785714
                           Computers, Office Equipment                     8347.571429
                           Information Technology Services                 1261.692308
                           Internet Services and Retailing                 1482.133333
                           Network and Other Communications Equipment      1350.500000
                           Scientific,Photographic and Control Equipment    778.833333
                           Semiconductors and Other Electronic Components  1074.826087
Telecommunications         Telecommunications                              3242.466667
Transportation             Airlines                                        2644.444444
                           Mail, Package, and Freight Delivery             2947.000000
                           Miscellaneous                                    227.000000
                           Railroads                                       1801.000000
                           Transportation Equipment                         487.600000
                           Transportation and Logistics                     179.000000
                           Trucking, Truck Leasing                          212.222222
Wholesalers                Miscellaneous                                     17.000000
                           Wholesalers: Diversified                         207.720000
                           Wholesalers: Electronics and Office Equipment    232.125000
                           Wholesalers: Food and Grocery                    194.333333

[79 rows x 2 columns]

In [116]:
g['Location','Profits'].max()

                                                                                          Location  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                                       Wichita, KS
Apparel                    Apparel                                               Winston-Salem, NC
Business Services          Advertising, marketing                                     New York, NY
                           Diversified Outsourcing Services                        San Leandro, CA
                           Education                                                   Phoenix, AZ
                           Financial Data Services                             Symmes Township, OH
                           Miscellaneous                                              Stamford, CT
                           Temporary Help                                                 Troy, MI
                           Waste Management                                      The Woodlands, TX
Chemicals                  Chemicals                                                Wilmington, DE
Energy                     Energy                                                   Washington, DC
                           Mining, Crude-Oil Production                                  Tulsa, OK
                           Miscellaneous                                              Voorhees, NJ
                           Oil and Gas Equipment, Services                               Tulsa, OK
                           Petroleum Refining                                           Warren, PA
                           Pipelines                                                     Tulsa, OK
                           Utilities: Gas and Electric                              Washington, DC
Engineering & Construction Engineering, Construction                               Watsonville, CA
                           Homebuilders                                             Scottsdale, AZ
Financials                 Commercial Banks                                      Winston-Salem, NC
                           Diversified Financials                                   Wilmington, DE
                           Insurance: Life, Health (Mutual)                        Springfield, MA
                           Insurance: Life, Health (stock)                            St. Paul, MN
                           Insurance: Property and Casualty (Mutual)            Woodland Hills, CA
                           Insurance: Property and Casualty (Stock)                  Worcester, MA
                           Real estate                                                  Toledo, OH
                           Securities                                          West Palm Beach, FL
Food and Drug Stores       Food and Drug Stores                                     Woonsocket, RI
Food, Beverages & Tobacco  Beverages                                                 Waterbury, VT
                           Food Consumer Products                                  Thomasville, GA
...                                                                                            ...
Materials                  Metals                                                   Wyomissing, PA
                           Miscellaneous                                          Santa Monica, CA
                           Packaging, Containers                                      Stamford, CT
Media                      Entertainment                                         Silver Spring, MD
                           Publishing, Printing                                         Sussex, WI
Motor Vehicles & Parts     Motor Vehicles and Parts                         Van Buren Township, MI
Retailing                  Automotive Retailing, Services                             Richmond, VA
                           General Merchandisers                                          York, PA
                           Specialty Retailers: Apparel                              St. Louis, MO
                           Specialty Retailers: Other                                   Winona, MN
Technology                 Computer Peripherals                                      Sunnyvale, CA
                           Computer Software                                      Santa Monica, CA
                           Computers, Office Equipment                                Stamford, CT
                           Information Technology Services                             Teaneck, NJ
                           Internet Services and Retailing                           Sunnyvale, CA
                           Network and Other Communications Equipment              Wallingford, CT
                           Scientific,Photographic and Control Equipment            Washington, DC
                           Semiconductors and Other Electronic Components               Woburn, MA
Telecommunications         Telecommunications                                         Stamford, CT
Transportation             Airlines                                                 St. George, UT
                           Mail, Package, and Freight Delivery                         Memphis, TN
                           Miscellaneous                                               Houston, TX
                           Railroads                                                     Omaha, NE
                           Transportation Equipment                                  Milwaukee, WI
                           Transportation and Logistics                                Seattle, WA
                           Trucking, Truck Leasing                                 Thomasville, NC
Wholesalers                Miscellaneous                                         Downers Grove, IL
                           Wholesalers: Diversified                                    Waltham, MA
                           Wholesalers: Electronics and Office Equipment                 Tempe, AZ
                           Wholesalers: Food and Grocery                   South San Francisco, CA

                                                                           Profits
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                              7608
Apparel                    Apparel                                            3273
Business Services          Advertising, marketing                             1094
                           Diversified Outsourcing Services                   1453
                           Education                                           140
                           Financial Data Services                            6328
                           Miscellaneous                                      1311
                           Temporary Help                                      419
                           Waste Management                                    753
Chemicals                  Chemicals                                          7685
Energy                     Energy                                              546
                           Mining, Crude-Oil Production                        941
                           Miscellaneous                                       476
                           Oil and Gas Equipment, Services                     501
                           Petroleum Refining                                16150
                           Pipelines                                          2521
                           Utilities: Gas and Electric                        2816
Engineering & Construction Engineering, Construction                           413
                           Homebuilders                                        803
Financials                 Commercial Banks                                  24442
                           Diversified Financials                            10954
                           Insurance: Life, Health (Mutual)                   1425
                           Insurance: Life, Health (stock)                    5642
                           Insurance: Property and Casualty (Mutual)          6229
                           Insurance: Property and Casualty (Stock)          24083
                           Real estate                                        1828
                           Securities                                         3345
Food and Drug Stores       Food and Drug Stores                               5237
Food, Beverages & Tobacco  Beverages                                          7351
                           Food Consumer Products                             7267
...                                                                            ...
Materials                  Metals                                              358
                           Miscellaneous                                         7
                           Packaging, Containers                               938
Media                      Entertainment                                      8382
                           Publishing, Printing                                151
Motor Vehicles & Parts     Motor Vehicles and Parts                           9687
Retailing                  Automotive Retailing, Services                      597
                           General Merchandisers                             14694
                           Specialty Retailers: Apparel                       2278
                           Specialty Retailers: Other                         7009
Technology                 Computer Peripherals                               1990
                           Computer Software                                 12193
                           Computers, Office Equipment                       53394
                           Information Technology Services                   13190
                           Internet Services and Retailing                   16348
                           Network and Other Communications Equipment         8981
                           Scientific,Photographic and Control Equipment      3357
                           Semiconductors and Other Electronic Components    11420
Telecommunications         Telecommunications                                17879
Transportation             Airlines                                           7610
                           Mail, Package, and Freight Delivery                4844
                           Miscellaneous                                       227
                           Railroads                                          4772
                           Transportation Equipment                            797
                           Transportation and Logistics                        510
                           Trucking, Truck Leasing                             427
Wholesalers                Miscellaneous                                        17
                           Wholesalers: Diversified                           1472
                           Wholesalers: Electronics and Office Equipment       572
                           Wholesalers: Food and Grocery                       687

[79 rows x 2 columns]

In [127]:
DFFort.nlargest(1,'Profits')

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000

In [121]:
df = pd.DataFrame(columns=DFFort.columns)

In [122]:
for city, data in g:
    highest_city_revenue = data.nlargest(1, 'Profits')
    df = df.append(highest_city_revenue)

In [123]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
45,United Technologies,Aerospace & Defense,Aerospace and Defense,"Farmington, CT",61047,7608,197200
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
186,Omnicom Group,Business Services,"Advertising, marketing","New York, NY",15134,1094,74900
248,ADP,Business Services,Diversified Outsourcing Services,"Roseland, NJ",11477,1453,55000
993,DeVry Education Group,Business Services,Education,"Downers Grove, IL",1910,140,11770
204,Visa,Business Services,Financial Data Services,"Foster City, CA",13880,6328,11300
870,Public Storage,Business Services,Miscellaneous,"Glendale, CA",2382,1311,5300
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
221,Waste Management,Business Services,Waste Management,"Houston, TX",12961,753,40600
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
633,First Solar,Energy,Energy,"Tempe, AZ",3579,546,6350
598,Antero Resources,Energy,"Mining, Crude-Oil Production","Denver, CO",3955,941,480
696,American Water Works,Energy,Miscellaneous,"Voorhees, NJ",3159,476,6700
319,Cameron International,Energy,"Oil and Gas Equipment, Services","Houston, TX",8782,501,23000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
104,Enterprise Products Partners,Energy,Pipelines,"Houston, TX",27028,2521,6800
115,Duke Energy,Energy,Utilities: Gas and Electric,"Charlotte, NC",24002,2816,29188
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
301,Lennar,Engineering & Construction,Homebuilders,"Miami, FL",9474,803,7749
23,J.P. Morgan Chase,Financials,Commercial Banks,"New York, NY",101006,24442,234598
16,Fannie Mae,Financials,Diversified Financials,"Washington, DC",110359,10954,7300
76,Massachusetts Mutual Life Insurance,Financials,"Insurance: Life, Health (Mutual)","Springfield, MA",38243,1425,11593
50,Prudential Financial,Financials,"Insurance: Life, Health (stock)","Newark, NJ",57119,5642,49384
35,State Farm Insurance Cos.,Financials,Insurance: Property and Casualty (Mutual),"Bloomington, IL",75697,6229,70425
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
488,Simon Property Group,Financials,Real estate,"Indianapolis, IN",5266,1828,4075
250,BlackRock,Financials,Securities,"New York, NY",11401,3345,13000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
62,Coca-Cola,"Food, Beverages & Tobacco",Beverages,"Atlanta, GA",44294,7351,123200
94,Mondelez International,"Food, Beverages & Tobacco",Food Consumer Products,"Deerfield, IL",29636,7267,99000
...,...,...,...,...,...,...,...
170,Nucor,Materials,Metals,"Charlotte, NC",16439,358,23700
426,A-Mark Precious Metals,Materials,Miscellaneous,"Santa Monica, CA",6070,7,52
127,International Paper,Materials,"Packaging, Containers","Memphis, TN",22365,938,56000
53,Disney,Media,Entertainment,"Burbank, CA",52465,8382,185000
255,R.R. Donnelley & Sons,Media,"Publishing, Printing","Chicago, IL",11257,151,68400
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
191,CarMax,Retailing,"Automotive Retailing, Services","Richmond, VA",14874,597,22064
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
89,TJX,Retailing,Specialty Retailers: Apparel,"Framingham, MA",30945,2278,216000
28,Home Depot,Retailing,Specialty Retailers: Other,"Atlanta, GA",88519,7009,385000
113,EMC,Technology,Computer Peripherals,"Hopkinton, MA",24704,1990,72000
25,Microsoft,Technology,Computer Software,"Redmond, WA",93580,12193,118000
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
31,IBM,Technology,Information Technology Services,"Armonk, NY",82461,13190,411798
36,Alphabet,Technology,Internet Services and Retailing,"Mountain View, CA",74989,16348,61814
54,Cisco Systems,Technology,Network and Other Communications Equipment,"San Jose, CA",49161,8981,71833
133,Danaher,Technology,"Scientific,Photographic and Control Equipment","Washington, DC",20909,3357,81000
51,Intel,Technology,Semiconductors and Other Electronic Components,"Santa Clara, CA",55355,11420,107300
13,Verizon,Telecommunications,Telecommunications,"New York, NY",131620,17879,177700
67,American Airlines Group,Transportation,Airlines,"Fort Worth, TX",40990,7610,118500
48,UPS,Transportation,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
930,Kirby,Transportation,Miscellaneous,"Houston, TX",2148,227,4200
129,Union Pacific,Transportation,Railroads,"Omaha, NE",21813,4772,47457
407,Trinity Industries,Transportation,Transportation Equipment,"Dallas, TX",6393,797,22030
208,C.H. Robinson Worldwide,Transportation,Transportation and Logistics,"Eden Prairie, MN",13476,510,13159
416,J.B. Hunt Transport Services,Transportation,"Trucking, Truck Leasing","Lowell, AR",6188,427,21562
315,Univar,Wholesalers,Miscellaneous,"Downers Grove, IL",8982,17,9200
320,HD Supply Holdings,Wholesalers,Wholesalers: Diversified,"Atlanta, GA",8779,1472,14000
102,Avnet,Wholesalers,Wholesalers: Electronics and Office Equipment,"Phoenix, AZ",27925,572,18800
57,Sysco,Wholesalers,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700